# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files


  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.3.0
#     hooks:
#       - id: check-added-large-files
#       - id: trailing-whitespace

#   - repo: local
#     hooks:
#       - id: isort
#         name: isort
#         stages: [commit]
#         #language: system
#         entry: isort
#         types: [python]

#       - id: black
#         name: black
#         stages: [commit]
#         #language: system
#         entry: black
#         types: [python]
